POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name" : "John Mark",
  "number": "123456"
}

### Empty name - should return error with status code 400
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name" : "",
  "number": "123456"
}

### Empty number - should return error with status code 400
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name" : "John Mark",
  "number": ""
}

### Unknown Endpoint
POST http://localhost:3001/unknown
Content-Type: application/json

{
  "name" : "John Jay",
  "number": "12345"
}